### ISSUE TITLE
Unable to run Lepardhttps://github.com/rabbityl/lepard/issues Code on modern GPUs

### ISSUE THREAD

**Issue by kartikeyavi** [rabbityl/lepard#39]
I am running Lepard on my laptop. I have an NVIDA 4060 Laptop GPU and am using WSL. When I am trying to run the code with the normal environment. It shows me the following error

`/root/anaconda3/envs/Lepard_old/lib/python3.8/site-packages/torch/cuda/__init__.py:104: UserWarning: 
NVIDIA GeForce RTX 4060 Laptop GPU with CUDA capability sm_89 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.
If you want to use the NVIDIA GeForce RTX 4060 Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/`

I installed pytorch again and with
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

But I got then I got the error 
`ImportError: /mnt/c/Users/Kartikeya Singh/Desktop/IIT KGP Work/3D_Reconstruction/Lepard/Lepard_PC/cpp_wrappers/cpp_subsampling/grid_subsampling.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv`

I have reinstalled ubuntu on WSL, CUDA, the NVIDIA Drivers. I have compiled the Cpp code again several times. But the error still persists. The error clearly lies in the cpp code, but I dont know CPP to debug it. @rabbityl a little help

**Comment by theros88** [comment]
The CUDA version must match the installed CUDA version of your system. Also torch should be 1.7.1 and torchvision 0.8.2
For example my CUDA version is 11.7 and I used the following pip install command on WSL and it worked:

> pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by kartikeyavi** [comment]
Worked well thanks
